### ISSUE TITLE
Tab not visible on 62.0.2

### ISSUE THREAD

**Issue by yeyeto2788** [mortalis13/Tabs-Export-XPI-Android#3]
Hello, 

I have encountered the issue where the tab does not show even loading all tabs. 

Is there a limit on the number of tabs to be exported?

System info:
Android 8.1.0
Firefox 62.0.2
Version used: 1.0.4

If you need any other info just let me know.

Regards.

**Comment by mortalis13** [comment]
Hi.
No limits for tabs number.
But there's a list of valid protocols for URLs:

- http://
- https://
- file://
- about:

In your situation you mean the number of lines in the exported text file is less than the number of opened tabs?

**Comment by yeyeto2788** [comment]
The problem is that the button/ta for exporting is not even available. All the urls are within the valid protocols you mentioned before.

At this moment I have 87 tabs on the browser and all of the tabs seems to be loaded so the button should be available to click on.

Is there a way to have the button available even after the the time set on the Extension's configuration?

Regards.

**Comment by mortalis13** [comment]
The button (actually a menu item "Tabs Export") visibility doesn't depend on number of opened tabs or the delay setting.
If the addon appears on the Add-ons browser page but the menu item is not shown then it could be an error when the addon was installed. Or maybe something in the browser blocks it. Didn't notice it earlier. If the addon has an error it just doesn't install and therefore is not listed.

Did you try to disable/enable, uninstall/install it?
Or could you try it on a fresh Firefox installation? If you don't want to reinstall your main Firefox try it with the Nightly edition (it also appears in the App Store if you search for "firefox").

During these poerations you could check the Console messages if it has any errors.
If you can connect your device via a USB cable to a PC and if you have Firefox of the same version on your PC these are the steps to view the Android Firefox console:

- on Android Firefox go to Settings -> Advanced -> Remote debugging via USB (on)
- on desktop Firefox press Shift+F8 (WebIDE)
- on the right press "Install ADB Helper"
- refresh or close and open WebIDE again
- if your device appears on the right click it
- on Android should appear a message to confirm remote connection
- if it connected right on the desktop press Main Process on the left, then Console at the bottom
- then perform some operations (disable/enable, reinstall) and check the console output

**Comment by yeyeto2788** [comment]
Hey @mortalis13 ,

It actually came out after some days (I saw the option yesterday) and it work with all tabs (Some of them where just not loaded in the time configured).

My guess is that I got the new fresh version of firefox updated 2 or 3 days before trying to use the extension. Is there any way this can be checked after an update (reinstall extension or activate it by default)?

On the other hand I'll try what you mentioned on the previous message on a tablet and see the output (If you need it, let me know and I can post it here.) and see if I'm able to reproduce the error.

Regards.

**Comment by mortalis13** [comment]
Well, I don't actually know what happens with addons when the browser is updated, will check it later.
But if it's listed in the installed addons and doesn't show in the menu, reactivating it or reinstalling should fix the problem. Maybe it was a special update which broke this particular addon. At least on the desktop I never faced problems with addons on Firefox updates.

And about the logs, see if get any error in the Console, and post it if it appears.

Now you have the "Tabs Export" menu item, right?

**Comment by yeyeto2788** [comment]
Yes, now I have the menu item :smile: so If you want we can close the issue and if I see errors on the installation I can open another issue for it.

**Comment by mortalis13** [comment]
OK. Thanks for your time.
