### ISSUE TITLE
Naming convention suggestion

### ISSUE THREAD

**Issue by duttyend** [mortalis13/Tabs-Export-XPI-Android#5]
Dear Mortalis,

First of all, big thanks for your awesome extensions !!!

I have a suggestion regarding the name of the backup files in order to facilitate sorting : 
Currently : tabs_export_17052019_134718
Suggestion : tabs_export_20190519_134718

This way, it is chronologically sorted automatically and one doesn't make a mistake restoring an older backup.

Thanks again and have a great day!

**Comment by mortalis13** [comment]
Hi.
No problem, check the version 1.0.5.
Thanks for your suggestion.
